### ISSUE TITLE
getInputBySchema 只有一种类型

### ISSUE THREAD

**Issue by coldrainc** [modern-js-dev/codesmith#59]
在使用getInputBySchema 传type不生效。只有一种list类型选项

**Comment by caohuilin** [comment]
> 在使用getInputBySchema 传type不生效。只有一种list类型选项

schema type 本身是 string[] 类型，目前只支持 ['string'] 和 ['number']，当你需要 input 类型时，不添加 items 字段即可，添加 items 字段就是 list 类型

**Comment by coldrainc** [comment]
您好，您发的邮件已收到

**Comment by coldrainc** [comment]
> > 在使用getInputBySchema 传type不生效。只有一种list类型选项
> 
> schema type 本身是 string[] 类型，目前只支持 ['string'] 和 ['number']，当你需要 input 类型时，不添加 items 字段即可，添加 items 字段就是 list 类型

其实是看用的inquirer, 能支持下对应的类型吗

**Comment by caohuilin** [comment]
@coldrainc 你需要使用什么类型呀

**Comment by coldrainc** [comment]
> 



> @coldrainc 你需要使用什么类型呀

**Comment by coldrainc** [comment]
> @coldrainc 你需要使用什么类型呀

能够支持正常的类型就行，checkbox，radio。我看是可以用的，只是这里是类型Schema有点奇怪

**Comment by caohuilin** [comment]
> > @coldrainc 你需要使用什么类型呀
> 
> 能够支持正常的类型就行，checkbox，radio。我看是可以用的，只是这里是类型Schema有点奇怪

嗯嗯 都可以用的，这里设计是为了兼容 UI 共用 schema 设计的
